#!/usr/bin/env bun
/**
 * create-shape.ts — Scaffold a new LibraryShapeDefinition.
 *
 * Usage:
 *   bun scripts/create-shape.ts <type> [--name "Display Name"] [--category flowchart|erd|uml-class|uml-usecase|basic|custom]
 *
 * Examples:
 *   bun scripts/create-shape.ts hexagon --name "Hexagon" --category flowchart
 *   bun scripts/create-shape.ts cloud --name "Cloud" --category basic
 *
 * Generates:
 *   src/shapes/library/<type>Shape.ts — Shape definition + handler + registration
 */

import { existsSync, writeFileSync } from 'fs';
import { resolve, join } from 'path';

// ── CLI argument parsing ────────────────────────────────────────────────────

const args = process.argv.slice(2);

if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
  console.log(`
Usage: bun scripts/create-shape.ts <type> [options]

Arguments:
  type               Shape type identifier (lowercase, e.g. "hexagon", "cloud")

Options:
  --name <name>      Display name (default: capitalized type)
  --category <cat>   Shape category: basic, flowchart, erd, uml-class, uml-usecase, custom
                     (default: flowchart)
  --width <n>        Default width  (default: 100)
  --height <n>       Default height (default: 80)
  --help, -h         Show this help message
`);
  process.exit(0);
}

const type = args[0]!;

function getFlag(flag: string): string | undefined {
  const idx = args.indexOf(flag);
  if (idx !== -1 && idx + 1 < args.length) return args[idx + 1];
  return undefined;
}

const displayName = getFlag('--name') ?? type.charAt(0).toUpperCase() + type.slice(1);
const category = getFlag('--category') ?? 'flowchart';
const defaultWidth = Number(getFlag('--width') ?? 100);
const defaultHeight = Number(getFlag('--height') ?? 80);

// ── Validation ──────────────────────────────────────────────────────────────

if (!/^[a-z][a-z0-9-]*$/.test(type)) {
  console.error(`Error: type "${type}" must be lowercase alphanumeric with hyphens (e.g. "my-shape").`);
  process.exit(1);
}

const validCategories = ['basic', 'flowchart', 'erd', 'uml-class', 'uml-usecase', 'uml-sequence', 'custom'];
if (!validCategories.includes(category)) {
  console.error(`Error: category "${category}" must be one of: ${validCategories.join(', ')}`);
  process.exit(1);
}

const pascalCase = type
  .split('-')
  .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
  .join('');

const outDir = resolve(import.meta.dir, '..', 'src', 'shapes', 'library');
const outFile = join(outDir, `${pascalCase}Shape.ts`);

if (existsSync(outFile)) {
  console.error(`Error: ${outFile} already exists.`);
  process.exit(1);
}

// ── Template ────────────────────────────────────────────────────────────────

const template = `/**
 * ${displayName} shape definition.
 *
 * Generated by: bun scripts/create-shape.ts ${type}
 */

import type { LibraryShapeDefinition } from './ShapeLibraryTypes';
import { createStandardAnchors } from './ShapeLibraryTypes';
import { createStandardProperties } from '../ShapeMetadata';
import { createLibraryShapeHandler } from './LibraryShapeHandler';
import { shapeRegistry } from '../ShapeRegistry';

/**
 * ${displayName} shape definition.
 *
 * The pathBuilder draws relative to the shape center (0, 0).
 * Width and height are passed so you can scale the geometry.
 */
const ${pascalCase}Shape: LibraryShapeDefinition = {
  type: '${type}',

  metadata: {
    type: '${type}',
    name: '${displayName}',
    category: '${category}',
    icon: '▢', // TODO: Choose an appropriate icon character
    properties: createStandardProperties({
      includeLabel: true,
      includeIcon: true,
    }),
    supportsLabel: true,
    supportsIcon: true,
    defaultWidth: ${defaultWidth},
    defaultHeight: ${defaultHeight},
  },

  /**
   * Build the shape path centered at origin.
   * Replace this with your custom geometry.
   */
  pathBuilder: (width: number, height: number) => {
    const path = new Path2D();
    const hw = width / 2;
    const hh = height / 2;

    // TODO: Replace with your shape geometry.
    // Default: simple rectangle
    path.rect(-hw, -hh, width, height);

    return path;
  },

  /**
   * Connector anchor points.
   * Standard 5-anchor pattern: center + top/right/bottom/left.
   * Replace with custom anchors if your shape is non-rectangular.
   */
  anchors: createStandardAnchors(),

  // hitTestMode: 'path',       // 'path' (accurate) or 'bounds' (fast)
  // customRender: undefined,   // Optional: extra rendering after fill/stroke
  // customLabelRendering: false,// Set true if customRender handles labels
  // dynamicAnchors: undefined, // Optional: instance-dependent anchors
};

// ── Registration ────────────────────────────────────────────────────────────

const handler = createLibraryShapeHandler(${pascalCase}Shape);
shapeRegistry.register('${type}', handler, ${pascalCase}Shape.metadata);

export { ${pascalCase}Shape };
`;

// ── Write file ──────────────────────────────────────────────────────────────

writeFileSync(outFile, template, 'utf-8');
console.log(`✓ Created ${outFile}`);
console.log(`\nNext steps:`);
console.log(`  1. Edit the pathBuilder in ${pascalCase}Shape.ts with your geometry`);
console.log(`  2. Import the file in your shape library barrel (e.g. flowchartShapes.ts)`);
console.log(`  3. Run \`bun run typecheck\` to verify`);
